### ISSUE TITLE
Duda formatear fecha

### ISSUE THREAD

**Issue by JonathanMarti** [JonathanMarti/practica_dwec_gestor_presupuesto#2]
Buenas @pedroprieto,
Estoy en la practica de fundamentos 3 tratando de formatear la fecha, en la funcion obtenerPeriodoAgrupacion y no consigo que se vea así '2021-09' cuando agrupo por mes, lo máximo que consigo es '2021-9' he mirado en los apuntes en el apartado de fecha y hora y no encuentro nada para solucionar eso.
![Image 001](https://user-images.githubusercontent.com/114580021/200654524-8bd1fec0-b002-43ec-b3a8-9a4d75f557d9.png)

**Comment by pedroprieto** [comment]
Buenas,

Puedes utilizar la función `toISOString()` (https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) y quedarte con el trozo que te interesa, utilizando `substring()` (https://javascript.info/string#getting-a-substring).

Un saludo!

**Comment by JonathanMarti** [comment]
Gracias Pedro, voy a darle un repaso a esos enlaces!
