### ISSUE TITLE
funcion agruparGastos

### ISSUE THREAD

**Issue by JonathanMarti** [JonathanMarti/practica_dwec_gestor_presupuesto#3]
Buenas @pedroprieto,
estoy atascado en la practica de fundamentos 3 de javascript, en concreto la funcion agruparGastos...
No se como abordarla, alguna pista o guía sobre por donde debería empezar?
Te paso lo que llevo hasta el momento...

funcion agruparGastos:

![Image 002](https://user-images.githubusercontent.com/114580021/201392941-3c5be394-7b1f-4464-a9fa-2bde4023f173.png)

funcion filtrarGastos:

![imagen](https://user-images.githubusercontent.com/114580021/201393192-7fb5602a-b63d-44f1-8575-505c445cee75.png)
![imagen](https://user-images.githubusercontent.com/114580021/201393338-7f849755-2f7f-4980-9776-2c9720101c61.png)

**Comment by pedroprieto** [comment]
Buenas,

Mejor sube el código a GitHub y te contesto por ahí.

`Object.keys` devuelve un array: por lo tanto, nunca va a ser 0. Si acaso, su propiedad `length` sí.

En la función de agrupar, `etiquetas` debe ser un array, no una lista de parámetros. 

En las grabaciones de las tutorías expliqué cómo abordar la función de agrupación. Échales un vistazo.

Un saludo!!
